kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
containerdConfigPatches:
- |-
  [plugins."io.containerd.grpc.v1.cri".registry.mirrors."{{ .Address }}"]
    endpoint = ["http://{{ .Address }}"]
  [plugins."io.containerd.grpc.v1.cri".registry.configs."{{ .Address }}".tls]
    insecure_skip_verify = true 